version: "3.8"

name: ${localWorkspaceFolderBasename}-devcontainer

services:
  app:
    image: ghcr.io/starburst997/devcontainer/personal-dev:latest
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  db:
    image: postgres:${templateOption:postgresVersion}
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

volumes:
  postgres-data:
